# Generated by Django 5.0.6 on 2024-08-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_task_vote_ratio_task_vote_total_review_task_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='task',
            name='vote_total',
        ),
    ]
