# Generated by Django 5.0.6 on 2024-08-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_task_tags_task_date_task_importance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
