# Generated by Django 5.0.6 on 2024-09-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_task_date_remove_task_time_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
